site_name: IDP Crossplane Compositions
nav:
  - Overview: index.md
  - XRDs:
      - PostgreSQLDatabase: xrds/postgresql-database.md
      - ApplicationEnvironment: xrds/application-environment.md
      - TeamInfraEnvironment: xrds/team-infra-environment.md
      - RabbitMQCluster: xrds/rabbitmq-cluster.md
      - RabbitMQInstance: xrds/rabbitmq-instance.md
plugins:
  - techdocs-core
