apiVersion: idp.rottler.io/v1alpha1
kind: RabbitMQCluster
metadata:
  name: team-a-rabbitmq
  namespace: team-a-infra
spec:
  team: team-a
  environment: homelab
  ha: false
  version: "3.13"
  storageSize: small
  allowedNamespaces:
    - team-a-order-management-order-service
