apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: team-infra-environment
  labels:
    # Kubernetes standard labels
    app.kubernetes.io/name: idp-crossplane-compositions
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/part-of: idp
    app.kubernetes.io/component: team-infra-environment
    # IDP labels
    idp.rottler.io/team: platform
    idp.rottler.io/system: idp
    idp.rottler.io/component: team-infra-environment
    # Crossplane integration
    crossplane.io/xrd: teaminfraenvironments.idp.rottler.io
spec:
  compositeTypeRef:
    apiVersion: idp.rottler.io/v1alpha1
    kind: TeamInfraEnvironment
  mode: Pipeline
  pipeline:
  - step: create-kubernetes-resources
    functionRef:
      name: crossplane-contrib-function-go-templating
    input:
      apiVersion: gotemplating.fn.crossplane.io/v1beta1
      kind: GoTemplate
      source: Inline
      inline:
        template: |
          {{- .Files.Get "files/teaminfraenvironments.idp.rottler.io/variables.yaml" | nindent 10 }}
          {{- .Files.Get "files/teaminfraenvironments.idp.rottler.io/namespace.yaml" | nindent 10 }}
          {{- .Files.Get "files/teaminfraenvironments.idp.rottler.io/argocd-application.yaml" | nindent 10 }}
          {{- .Files.Get "files/teaminfraenvironments.idp.rottler.io/argocd-repo-secret.yaml" | nindent 10 }}
  - step: automatically-detect-ready-composed-resources
    functionRef:
      name: crossplane-contrib-function-auto-ready
