{{- if $hpaEnabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $xrName }}
  labels:
    {{- range $key, $value := $labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $xrName }}
  minReplicas: {{ $min }}
  maxReplicas: {{ $max | int }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $targetCPU }}
{{- end }}
