---
apiVersion: v1
kind: Service
metadata:
  name: {{ $xrName }}
  labels:
    {{- range $key, $value := $labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ $port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- range $key, $value := $selectorLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
