apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane:custom:key-value-store
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
    app.kubernetes.io/name: idp-crossplane-compositions
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/part-of: idp
    app.kubernetes.io/component: key-value-store
    idp.rottler.io/team: platform
    idp.rottler.io/system: idp
    idp.rottler.io/component: key-value-store
rules:
- apiGroups:
  - dragonflydb.io
  resources:
  - dragonflies
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - dragonflydb.io
  resources:
  - dragonflies/status
  verbs:
  - get
  - list
  - watch
