---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-%s-%s" $team $system $component }}
  namespace: argocd
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: argocd-application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $team }}

  source:
    repoURL: {{ printf "https://gitlab.home.rottlr.de/idp/%s/%s-%s-deployment.git" $team $system $component }}
    targetRevision: {{ if or (eq $environment "homelab") (eq $environment "development")}}development{{ else }}main{{end}}
    path: ./
    helm:
      releaseName: {{ printf "%s-%s-%s" $team $system $component }}
      valueFiles:
        - values.yaml
        - environments/{{ $environment }}.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ printf "%s-%s-%s" $team $system $component }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
