{{- if not $targetNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ printf "%s-%s-%s" $team $system $component }}
  annotations:
    gotemplating.fn.crossplane.io/composition-resource-name: namespace
spec: {}
{{- end }}
